# Generated by Django 3.2.12 on 2023-11-06 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_auto_20231106_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user_id',
            new_name='user',
        ),
    ]
