# Generated by Django 3.2.12 on 2023-11-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0003_auto_20231106_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cost',
            field=models.IntegerField(null=True),
        ),
    ]
